version: '3.8'

services:
  localstack:
    container_name: localstack-test
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ec2,ecs,elbv2,iam,logs,secretsmanager,sts
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localhost
      - LS_LOG=trace
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/tmp/localstack"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s