"""Create SQLModel tables

Revision ID: d0024d5055af
Revises: 
Create Date: 2025-07-14 12:20:34.194960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0024d5055af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_verified', sa.DateTime(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('github_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_table('verification_tokens',
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('identifier'),
    sa.UniqueConstraint('token')
    )
    op.create_table('webhooks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('git_repo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('git_repo_url')
    )
    op.create_table('accounts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refresh_token_expires_in', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_table('teams',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_aws_configs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aws_access_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aws_secret_access_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aws_region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('projects',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('git_repo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'CLONING', 'BUILDING', 'DEPLOYING', 'DEPLOYED', 'FAILED', name='projectstatus'), nullable=False),
    sa.Column('ecs_cluster_arn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ecs_service_arn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alb_arn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('existing_vpc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('existing_subnet_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('existing_cluster_arn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=False),
    sa.Column('memory', sa.Integer(), nullable=False),
    sa.Column('disk_size', sa.Integer(), nullable=False),
    sa.Column('subdirectory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('health_check_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auto_deploy_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('webhook_configured', sa.Boolean(), nullable=False),
    sa.Column('is_web_service', sa.Boolean(), nullable=False),
    sa.Column('container_command', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secrets_arn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_aws_configs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aws_access_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aws_secret_access_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aws_region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='teammemberrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_aws_config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PROVISIONING', 'DEPLOYING', 'DEPLOYED', 'FAILED', 'DELETING', name='environmentstatus'), nullable=False),
    sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpu', sa.Integer(), nullable=False),
    sa.Column('memory', sa.Integer(), nullable=False),
    sa.Column('disk_size', sa.Integer(), nullable=False),
    sa.Column('existing_vpc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('existing_subnet_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('existing_cluster_arn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ecs_cluster_arn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ecs_service_arn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alb_arn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alb_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('task_definition_arn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secrets_arn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['team_aws_config_id'], ['team_aws_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('environment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'BUILDING', 'PUSHING', 'PROVISIONING', 'DEPLOYING', 'SUCCESS', 'FAILED', name='deploymentstatus'), nullable=False),
    sa.Column('image_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('commit_sha', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('environment_variables',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('environment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Temporarily disabled: drop old Prisma tables to avoid data loss
    # These will be handled in a separate migration after data migration
    # op.drop_table('Deployment')
    # op.drop_index('VerificationToken_identifier_token_key', table_name='VerificationToken')
    # op.drop_index('VerificationToken_token_key', table_name='VerificationToken')
    # op.drop_table('VerificationToken')
    # op.drop_table('Project')
    # op.drop_index('User_email_key', table_name='User')
    # op.drop_index('User_githubId_key', table_name='User')
    # op.drop_table('User')
    # op.drop_index('Webhook_gitRepoUrl_key', table_name='Webhook')
    # op.drop_table('Webhook')
    # op.drop_index('Session_sessionToken_key', table_name='Session')
    # op.drop_table('Session')
    # op.drop_index('EnvironmentVariable_projectId_key_key', table_name='EnvironmentVariable')
    # op.drop_table('EnvironmentVariable')
    # op.drop_index('TeamAwsConfig_teamId_name_key', table_name='TeamAwsConfig')
    # op.drop_table('TeamAwsConfig')
    # op.drop_table('Team')
    # op.drop_index('TeamMember_teamId_userId_key', table_name='TeamMember')
    # op.drop_table('TeamMember')
    # op.drop_index('Environment_projectId_name_key', table_name='Environment')
    # op.drop_table('Environment')
    # op.drop_index('Account_provider_providerAccountId_key', table_name='Account')
    # op.drop_table('Account')
    # op.drop_index('UserAWSConfig_userId_key', table_name='UserAWSConfig')
    # op.drop_table('UserAWSConfig')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserAWSConfig',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('awsAccessKeyId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('awsSecretAccessKey', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('awsRegion', sa.TEXT(), server_default=sa.text("'us-east-1'::text"), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='UserAWSConfig_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='UserAWSConfig_pkey')
    )
    op.create_index('UserAWSConfig_userId_key', 'UserAWSConfig', ['userId'], unique=True)
    op.create_table('Account',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('providerAccountId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('scope', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refresh_token_expires_in', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='Account_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Account_pkey')
    )
    op.create_index('Account_provider_providerAccountId_key', 'Account', ['provider', 'providerAccountId'], unique=True)
    op.create_table('Environment',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('teamAwsConfigId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('CREATED', 'PROVISIONING', 'DEPLOYING', 'DEPLOYED', 'FAILED', 'DELETING', name='EnvironmentStatus'), server_default=sa.text('\'CREATED\'::"EnvironmentStatus"'), autoincrement=False, nullable=False),
    sa.Column('branch', sa.TEXT(), server_default=sa.text("'main'::text"), autoincrement=False, nullable=False),
    sa.Column('cpu', sa.INTEGER(), server_default=sa.text('256'), autoincrement=False, nullable=False),
    sa.Column('memory', sa.INTEGER(), server_default=sa.text('512'), autoincrement=False, nullable=False),
    sa.Column('diskSize', sa.INTEGER(), server_default=sa.text('21'), autoincrement=False, nullable=False),
    sa.Column('existingVpcId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('existingSubnetIds', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('existingClusterArn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ecsClusterArn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ecsServiceArn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('albArn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('albName', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('taskDefinitionArn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('secretsArn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name='Environment_projectId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teamAwsConfigId'], ['TeamAwsConfig.id'], name='Environment_teamAwsConfigId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Environment_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('Environment_projectId_name_key', 'Environment', ['projectId', 'name'], unique=True)
    op.create_table('TeamMember',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('teamId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'ADMIN', 'MEMBER', name='TeamMemberRole'), server_default=sa.text('\'MEMBER\'::"TeamMemberRole"'), autoincrement=False, nullable=False),
    sa.Column('joinedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['Team.id'], name='TeamMember_teamId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='TeamMember_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='TeamMember_pkey')
    )
    op.create_index('TeamMember_teamId_userId_key', 'TeamMember', ['teamId', 'userId'], unique=True)
    op.create_table('Team',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ownerId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ownerId'], ['User.id'], name='Team_ownerId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Team_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('TeamAwsConfig',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('teamId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('awsAccessKeyId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('awsSecretAccessKey', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('awsRegion', sa.TEXT(), server_default=sa.text("'us-east-1'::text"), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['Team.id'], name='TeamAwsConfig_teamId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='TeamAwsConfig_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('TeamAwsConfig_teamId_name_key', 'TeamAwsConfig', ['teamId', 'name'], unique=True)
    op.create_table('EnvironmentVariable',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('environmentId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('isSecret', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('secretKey', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['environmentId'], ['Environment.id'], name='EnvironmentVariable_environmentId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name='EnvironmentVariable_projectId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='EnvironmentVariable_pkey')
    )
    op.create_index('EnvironmentVariable_projectId_key_key', 'EnvironmentVariable', ['projectId', 'key'], unique=True)
    op.create_table('Session',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sessionToken', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='Session_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Session_pkey')
    )
    op.create_index('Session_sessionToken_key', 'Session', ['sessionToken'], unique=True)
    op.create_table('Webhook',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('gitRepoUrl', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('secret', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('isActive', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Webhook_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('Webhook_gitRepoUrl_key', 'Webhook', ['gitRepoUrl'], unique=True)
    op.create_table('User',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('emailVerified', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=True),
    sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('githubId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('User_githubId_key', 'User', ['githubId'], unique=True)
    op.create_index('User_email_key', 'User', ['email'], unique=True)
    op.create_table('Project',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('gitRepoUrl', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('branch', sa.TEXT(), server_default=sa.text("'main'::text"), autoincrement=False, nullable=False),
    sa.Column('userId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('teamId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('CREATED', 'CLONING', 'BUILDING', 'DEPLOYING', 'DEPLOYED', 'FAILED', name='ProjectStatus'), server_default=sa.text('\'CREATED\'::"ProjectStatus"'), autoincrement=False, nullable=False),
    sa.Column('ecsClusterArn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ecsServiceArn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('albArn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('existingVpcId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('existingSubnetIds', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('existingClusterArn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cpu', sa.INTEGER(), server_default=sa.text('256'), autoincrement=False, nullable=False),
    sa.Column('memory', sa.INTEGER(), server_default=sa.text('512'), autoincrement=False, nullable=False),
    sa.Column('diskSize', sa.INTEGER(), server_default=sa.text('21'), autoincrement=False, nullable=False),
    sa.Column('subdirectory', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('port', sa.INTEGER(), server_default=sa.text('3000'), autoincrement=False, nullable=False),
    sa.Column('healthCheckPath', sa.TEXT(), server_default=sa.text("'/health'::text"), autoincrement=False, nullable=False),
    sa.Column('autoDeployEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('webhookId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('webhookConfigured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('secretsArn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['Team.id'], name='Project_teamId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='Project_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webhookId'], ['Webhook.id'], name='Project_webhookId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='Project_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('VerificationToken',
    sa.Column('identifier', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False)
    )
    op.create_index('VerificationToken_token_key', 'VerificationToken', ['token'], unique=True)
    op.create_index('VerificationToken_identifier_token_key', 'VerificationToken', ['identifier', 'token'], unique=True)
    op.create_table('Deployment',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('projectId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('environmentId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'BUILDING', 'PUSHING', 'PROVISIONING', 'DEPLOYING', 'SUCCESS', 'FAILED', name='DeploymentStatus'), server_default=sa.text('\'PENDING\'::"DeploymentStatus"'), autoincrement=False, nullable=False),
    sa.Column('imageTag', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('commitSha', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('celeryTaskId', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['environmentId'], ['Environment.id'], name='Deployment_environmentId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name='Deployment_projectId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Deployment_pkey')
    )
    op.drop_table('environment_variables')
    op.drop_table('deployments')
    op.drop_table('environments')
    op.drop_table('team_members')
    op.drop_table('team_aws_configs')
    op.drop_table('projects')
    op.drop_table('user_aws_configs')
    op.drop_table('teams')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('accounts')
    op.drop_table('webhooks')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
